language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t letsya68/react-test -f ./client/Dockerfile.dev ./client

sript:
  - docker run -e CI=true letsya68/react-test npm run test


after_success:
  - docker build -t letsya68/multi-client ./client
  - docker build -t letsya68/multi-nginx ./nginx
  - docker build -t letsya68/multi-server ./server
  - docker build -t letsya68/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take these images and push them to docker hub
  - docker push letsya68/multi-client
  - docker push letsya68/multi-nginx
  - docker push letsya68/multi-server
  - docker push letsya68/multi-worker

